version: '3.8'

networks:
  default:
    driver: bridge

services:
  epg-filter:
    image: epgfilterapp:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app  # Optional: Mount the current directory for live updates (remove for production)
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - default