version: '3.8'

services:
  epg-filter:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    deploy:
      restart_policy:
        condition: on-failure
