version: '2.4'
services:
  epgfilter:
    container_name: epgfilter
    image: epgfilterapp:latest
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 on the host
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app  # Optional: Mount the current directory for live updates (remove for production)
    restart: unless-stopped
