version: '3.8'

services:
  epgfilter:
    container_name: epgfilter
    image: liranhg/epgfilter:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
