version: '2.4'

services:
  epgfilter:
    image: liranhg/epgfilter:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
